- pandas_market_calendars/market_calendar.py
- tests/test_eurex_calendar.py
- tests/test_nyse_calendar.py
Whereas the timestamp being equal to the open means the market is indeed open, if the timestamp is equal to the close it means the market is closed.  This extremely minor change fixes that, in addition to fixing a typo.  Let me know if you have any questions or disagree.  Thanks!
> Timestamp must be before the close for the market to be open

- pandas_market_calendars/calendar_utils.py
- pandas_market_calendars/exchange_calendar_jpx.py
- tests/test_jpx_calendar.py
Takes into account Japanese public holidays and lunch time closures.
> Add calendar for the JPX stock exchange

- pandas_market_calendars/exchange_calendar_nyse.py
- pandas_market_calendars/us_holidays.py
- tests/test_nyse_calendar.py
Add 1985-09-27 as a date the NYSE market was closed. http://s3.amazonaws.com/armstrongeconomics-wp/2013/07/NYSE-Closings.pdf has other dates that may be of interest. I confirmed that Yahoo historical finance data does not contain an entry for 1985-09-27.
> NYSE was closed 1985-09-27 for Hurricane Gloria.

- README.rst
- docs/new_market.rst
- pandas_market_calendars/__init__.py
- pandas_market_calendars/calendar_registry.py
- pandas_market_calendars/calendar_utils.py
- pandas_market_calendars/class_registry.py
- pandas_market_calendars/exchange_calendar_bmf.py
- pandas_market_calendars/exchange_calendar_cfe.py
- pandas_market_calendars/exchange_calendar_cme.py
- pandas_market_calendars/exchange_calendar_eurex.py
- pandas_market_calendars/exchange_calendar_ice.py
- pandas_market_calendars/exchange_calendar_jpx.py
- pandas_market_calendars/exchange_calendar_lse.py
- pandas_market_calendars/exchange_calendar_nyse.py
- pandas_market_calendars/exchange_calendar_six.py
- pandas_market_calendars/exchange_calendar_tsx.py
- pandas_market_calendars/market_calendar.py
- tests/test_class_registry.py
- tests/test_market_calendar.py
Implementation of feature request #43:
-  Calendar registration happens automatically by deriving from MarketCalendar.
-  Calendars are registered under their aliases (provided as a class attribute "aliases").
-  If a Calendar class does not have an "aliases" attribute, the class name is used instead.
-  A list of registered calendars can be retrieved with "get_calendar_names".
-  Registered calendars can be instantiated as before, e.g. get_calendar('NYSE').
-  Some attributes of calendar_utils are marked as deprecated (get_calendar, _calendars, _aliases). They can be removed in the future.
Currently get_calendar_names returns:
['CFE', 'ICE', 'ICEUS', 'NYFE', 'NYSE', 'stock', 'NASDAQ', 'BATS', 'CME', 'CBOT', 'COMEX', 'NYMEX', 'BMF', 'LSE', 'TSX', 'TSXV', 'EUREX', 'SIX', 'JPX']
> Automatic calendar registration

- docs/calendars.rst
- docs/pandas_market_calendars.rst
- pandas_market_calendars/calendar_registry.py
- pandas_market_calendars/exchange_calendar_ose.py
- tests/test_ose_calendar.py
Hey, so I implemented the Oslo Stock Exchange. Was only able to find the dates for 2017, 2018 and 2019 for validation. 
Appreciate any feedback.
From commit message:
Oslo Stock Exchange holiday calendar. The trading times are for the equities (other instruments have other opening/closing times).
I can only find dates for 2017, 2018 and 2019 for now, but will see if anyone can supplement me with the ones for the last decade.
Unit tests are passing.
Documents updated and removed unused (jpx\_autumnal\_equinox module).
Removed unused imports
> Implemented OSE (Oslo Stock Exchange)

- pandas_market_calendars/calendar_registry.py
- pandas_market_calendars/exchange_calendar_nyse.py
- pandas_market_calendars/us_holidays.py
This is the PR #53 without the addition of the imports in the calendar_registry.py file which are not needed.
> Add GHW Bush Day of Mourning (2018-12-5, NYSE)

- pandas_market_calendars/exchange_calendar_jpx.py
- pandas_market_calendars/holidays_jp.py
- tests/test_jpx_calendar.py
Japan did a 10 day holiday to mark the ascension of the new emperor
> add JPX Ascension Day holidays for 2019

- pandas_market_calendars/exchange_calendar_eurex.py
ETF and ETC based on Xetra: trading and exercise closed
german equity index options: trading and exercise closed (e.g. ODAX)
german equity index futures: are trading (e.g. FDAX)
german interest rate derivatives are trading (e.g. FGBM)
derivatives with underlying having its primary listing outside germany are trading (e.g. KOSPI)
https://www.eurexchange.com/exchange-en/trading/trading-calendar/holiday-regulations
> added german national holiday

- docs/change_log.rst
- pandas_market_calendars/market_calendar.py
- tests/test_market_calendar.py
This is finally addressing issue #42. The idea is to supply a timezone to schedule() in order to convert open/close times to a certain timezone, like US/Eastern. I figured instead of using an if/else block, we could just convert the timezone directly on the open/close dataframes even though this may be a tiny bit of extra compute overhead for the default UTC.
> Add timezone functionality to schedule()

- pandas_market_calendars/market_calendar.py
- tests/test_market_calendar.py
'MarketCalendar._get_current_time' uses UTC time because 'MarketCalendar.schedule' is currently based on UTC time 'Market.Calendar.valid_days'.
IMO this justifies the elaborate mock test case (can't find a better way to mock system time) - as it can serve as a basis to create similar tests later on.
> #87 Add is open now

- pandas_market_calendars/market_calendar.py
Addresses #108 
Cache holidays computation in order to improve running time of repeated valid_days calls.
> Cache holidays

- README.rst
- docs/calendars.rst
- docs/change_log.rst
- pandas_market_calendars/__init__.py
- pandas_market_calendars/calendar_registry.py
- pandas_market_calendars/market_calendar.py
- pandas_market_calendars/trading_calendars.py
- setup.py
- tests/test_market_calendar.py
pandas_market_calendars now provides all the calendars in the https://github.com/quantopian/trading_calendars project as the first phase of the merger.
> Merge phase1.0

- pandas_market_calendars/market_calendar.py
- tests/test_bse_calendar.py
- tests/test_market_calendar.py
- tests/test_ose_calendar.py
This would be my proposed solution for #164, including an update to the tests.
@rsheftel, I think that it would be better to raise an error if a timestamp is passed that falls outside of the range covered by the schedule instead of returning False. Some tests are failing because I already implemented that. I wanted to see if you agree before adjusting those tests?
Thanks
> open_at_time fix

- pandas_market_calendars/holidays_oz.py
Looks like a typo slipped into the holiday calendar for Australia. Australia Day should be on 26 January, not 27. This fixes the typo.
Context: https://info.australia.gov.au/about-australia/special-dates-and-events/public-holidays
> Fix the date for Australia Day

- pandas_market_calendars/exchange_calendar_nyse.py
- pandas_market_calendars/market_calendar.py
DatetimeIndex.union_many() is deprecated as of pandas 1.4.0. This PR replaces union_many() in [market_calendar.py](https://github.com/rsheftel/pandas_market_calendars/blob/master/pandas_market_calendars/market_calendar.py) and [exchange_calendar_nyse.py](https://github.com/rsheftel/pandas_market_calendars/blob/master/pandas_market_calendars/exchange_calendar_nyse.py).
Tests now run without warning. Closes #168
> Fix deprecation warning with pandas 1.4.0

- pandas_market_calendars/exchange_calendar_asx.py
- pandas_market_calendars/holidays_oz.py
- tests/test_asx_calendar.py
Used the correct rule to move Boxing Day to Tuesday when Christmas falls on a Saturday.
Closes #169
Reference: https://en.wikipedia.org/wiki/Public_holidays_in_Australia#:~:text=If%20Christmas%20Day%20(25%20December,is%20also%20a%20public%20holiday.
> Fix calculation of Boxing Day additional day for Australia, add tests

- pandas_market_calendars/calendar_registry.py
- pandas_market_calendars/exchange_calendar_sifma.py
- pandas_market_calendars/holidays_sifma.py
- tests/test_sifma_calendars.py
Support for SIFMA Calendars.
US: Tested  2019 thru 2023
UK: Tested  2020 thru 2023 
JP: Tested  2022
Note: AbstractHolidayCalendar.start_date commented out on line 76 of exchange_calendar_sifma.py as it causes other tests to fail when run together. Uncommented, all tests run individually. I'm not sure how to re-initialize it. This is a test-only issue but the calendar really shouldn't be valid prior to 1998.
> Added SIFMA US, UK, and JP Calendars

- pandas_market_calendars/calendar_registry.py
- pandas_market_calendars/exchange_calendar_iex.py
- tests/test_iex_calendar.py
I did not create a dedicated `holidays_iex` file because I wanted to keep this as much of a NYSECalendar derivative as I could. 
I spoke to [Ronan Ryan](https://iex.io/about/leadership/ronan-ryan/) a few weeks ago and he mentioned a fault in one of IEX's matching engines that caused a temporary trade halt but I cannot find a date or time for that event. Other than that, there are no extra Ad-hoc events in IEX's relatively short operation time. If I can find it, I will add it in.
This closes #181
> IEX Exchange Calendar

- .travis.yml
- setup.py
- tests/test_market_calendar.py
* Sets minimum python to 3.8
* Adjusts test to work with the new schedule layout
* Increments pandas_market_calendars to version 3.5 in setup.py
> Adjustments for exchange_calendars v4

- pandas_market_calendars/exchange_calendar_bmf.py
- tests/test_bmf_calendar.py
1. Removed regional holidays from 2022 forward
2. Removed two cancelled holidays due to covid in 2020
3. Added 'B3' as alias
4. added tests for the above behaviors
Detailed explanation can be found in issue #188.
Note: Since the two cancelled holidays in 2020 were the regional ones removed in 2022, and I found no way to "override" a holiday and force a open market day, I implemented these as such:
- Regular holiday until 2019
- Adhoc  holiday in 2021
This might seem a duplicate from PR #165, but their implementation removed those holidays from the entire history, not from 2022 forward. Their implementation also did not cover the 2020 skips.
> Adjust BMF calendar for regional holidays and covid calendar changes

- README.rst
- docs/change_log.rst
- docs/new_market.rst
- examples/usage.ipynb
- pandas_market_calendars/calendar_utils.py
- pandas_market_calendars/class_registry.py
- pandas_market_calendars/exchange_calendar_nyse.py
- pandas_market_calendars/exchange_calendars_mirror.py
- pandas_market_calendars/market_calendar.py
- tests/test_class_registry.py
- tests/test_iex_calendar.py
- tests/test_market_calendar.py
- tests/test_nyse_calendar.py
- tests/test_utils.py
This PR covers all the proposed changes in #198 (and #209). 
Backwards Incompatible Changes:
* MarketCalendar.days_at_time now returns a Series instead of a DatetimeIndex,  which is needed for allowing offsets in special times. 
Other Changes:
* The property `interruptions` is now available to include data on interruptions
* The property `interruptions_df` provides these interruptions in a concise dataframe
* MarketCalendar.schedule has an extra kwarg ` interruptions`, which controls whether interruptions are added to the schedule as extra columns
* open_at_time can handle schedules with breaks and any number of interruptions.
* there is an additional class member, `open_close_map`, that indicates which market times to consider opens or closes.
* times in special_* properties can be …
> Extraordinary market times

- tests/test_exchange_calendar_cme_globex_energy_and_metals.py
With @Stryder-Git new framework, the CME Globex Energy and Metals no special opens test now runs.
One thing I noticed, test_market_calendar.py now takes 10's of minutes to run. I didn't change that test. It has the same behavior before and after my test modification.
> CME Globex Energy and Metals no special opens test

- pandas_market_calendars/calendar_registry.py
Currently, the implicit return type for the `get_calendar` function is `None` while the actual return type of `get_calendar` is `MarketCalendar` due to the inferred `MarketCalendar.factory` function. This pull request adds the correct type hint for the `get_calendar` function.
> Add type hint for get calendar function

- tests/test_nyse_calendar_early_years.py
Added tests for 2024 and 2025 to the NYSE calendar.
No rules updates were required.
https://www.nyse.com/markets/hours-calendars
> NYSE tests for 2024 and 2025

- .gitignore
- pandas_market_calendars/exchange_calendar_cboe.py
- pandas_market_calendars/holidays_nyse.py
- pandas_market_calendars/holidays_us.py
- pandas_market_calendars/market_calendar.py
- tests/test_cboe_calendars.py
- tests/test_market_calendar.py
- tests/test_nyse_calendar.py
Various fixes to support Pandas 2.1.x where Index.map() no longer passes through the index, it only passes through the elements of the index, and date time parsing is more eager to use second-level granularity rather than ns level.
Targeting #279 
Also fixes #250 / #265.
Apologies for the previous pull request, I was still pointing to a different base repo and needed to clean up my fork.
> Various fixes to support Pandas 2.1.x

- docs/calendars.rst
I added IEX a few months ago and forgot to add it to docs
> Add IEX To calendars documentation

- docs/calendars.rst
- pandas_market_calendars/calendar_registry.py
- pandas_market_calendars/calendars/eurex_fixed_income.py
- tests/test_eurex_fixed_income_calendar.py
Added a calendar for EUREX fixed income products
Tickers: FGBM, FGBL, FGBS, FGBX
https://www.tradinghours.com/markets/eurex
https://www.eurex.com/resource/blob/3378814/910cf372738890f691bc1bfbccfd3aef/data/tradingcalendar_2023_en.pdf
> Add EUREX fixed income calendar

- pandas_market_calendars/calendars/bmf.py
- tests/test_bmf_calendar.py
Added holiday to BMF calendar for when New Year's Eve falls on Sunday. Previous holiday occurrences can be seen in 1995, 2000, 2006, 2017 and 2023 (ticker BMFBOVESPA:IBOV on TradingView is the main stock index).
> Added BMF calendar holiday for New Year's Eve on Sunday

- pandas_market_calendars/calendars/bmf.py
- tests/test_bmf_calendar.py
Added new national holiday (Black Awareness Day) on November 20th starting in 2024. The same date was a municipal holiday until 2021.
The new holiday is officially added through "Circular Letter 215/2023", published on 2023-12-22 and available [here](https://www.b3.com.br/data/files/FE/25/60/54/D339C8103152D4C8AC094EA8/OC%20215-2023%20PRE%20Calendario%20de%20Feriados%202024%20-%20Feriado%2020.11(EN).pdf).
Excerpt:
The latest official BMF calendar can be verified [here](https://www.b3.com.br/en_us/solutions/platforms/puma-trading-system/for-members-and-traders/trading-calendar/holidays/).
I will add new tests next. Because of the old holiday on the same date, the previous test has to be modified with an end date.
> Added national holiday for BMF calendar (Black Awareness Day, Nov 20th)

- pandas_market_calendars/holidays/cn.py
According to government schedule 2024 CNY's Eve is not a public holiday, but the market was not open on that day.
> Fixed 2024 CNY's Eve

- pandas_market_calendars/calendars/eurex.py
Remove German National Day from Eurex holidays
In the calendars available in [Eurex Trading calendar archive](https://www.eurex.com/ex-en/trade/trading-calendar/trading-calendar-archive/) (that go back to the year 2000), the German National Day is only a holiday for "German equity and equity index derivatives as well as ETF and ETC derivatives, which are based on Xetra® listing" (starts appearing in 2014). There are years (for instance 2017) for which there are more holidays for Germany.
> Remove German National Day from Eurex holidays

- pandas_market_calendars/calendars/jpx.py
- tests/test_jpx_calendar.py
Pull Request addresses Issue #350.
Issue #350 stems from the JPX market closing time, which has been extended to 15:30 (local time) starting from 2024-11-05. The current implementation does not reflect this change, resulting in an incorrect closing time of 15:00 (local time).
This update modifies the market closing time in the `JPXExchangeCalendar` class to reflect the new closing time.
> Update market close of JPX to 15:30

- pandas_market_calendars/market_calendar.py
Small, but notable, performance increase to the _tryholidays() function.
In testing I found that generating market calendars and date ranges comprised a significant portion of what my code was spending time doing. While the majority of the time spent is in panda's date_range function I did find that the _tryholidays function was abnormally slow. 
It turns out that some calendars, such as NYSE, use Holiday Calendars for Special opens/closes that behave more like Ad-hoc Days as than Holidays. This is a format that Exchange Calendars follows as well. Currently when making a schedule, these dates are retrieved through Pandas' Holiday Calendar System which is designed around reoccurring holidays making the date retrieval far slower than it needs to be.
I added a check that manually retrieves …
> Schedule Generation Performance Optimization

- pandas_market_calendars/calendars/nyse.py
- pandas_market_calendars/holidays/nyse.py
https://www.bloomberg.com/news/articles/2024-12-30/us-stock-market-to-close-jan-9-on-day-of-mourning-for-carter
> Add Jimmy Carter memorial closure.

- docs/change_log.rst
- examples/usage.ipynb
- pandas_market_calendars/__init__.py
- pandas_market_calendars/calendar_utils.py
- pandas_market_calendars/calendars/iex.py
- pandas_market_calendars/calendars/nyse.py
- pandas_market_calendars/calendars/tase.py
- pandas_market_calendars/market_calendar.py
- tests/test_date_range.py
- tests/test_iex_calendar.py
- tests/test_market_calendar.py
- tests/test_nyse_calendar_early_years.py
- tests/test_utils.py
As Noted in the update log this PR brings the following:
- Added mark_session() Util Function
- Added MarketCalendar.date_range_htf() Method
- Added MarketCalendar.schedule_from_days() Method
The only thing of note that may not be backwards compatible with *every* user's implementation is the following change:
- Split NYSE Holiday Calendar into Two Calendars to support Date_Range_HTF()
- NYSE.weekmask now returns "Mon Tue Wed Thur Fri" instead of "Mon Tue Wed Thur Fri Sat"
This was needed to make Date_Range_HTF() Work properly. In theory it should also make nyse schedule generation faster, but the difference is likely negligible. ** This doesn't effect the schedule. NYSE still produces Saturdays pre-1952, it just does so using a different implementation.
For Information on the features …
> Additional Features

- pandas_market_calendars/calendars/asx.py
- pandas_market_calendars/calendars/bse.py
- pandas_market_calendars/calendars/cboe.py
- pandas_market_calendars/calendars/hkex.py
- pandas_market_calendars/calendars/iex.py
- pandas_market_calendars/calendars/jpx.py
- pandas_market_calendars/calendars/lse.py
- pandas_market_calendars/calendars/nyse.py
- pandas_market_calendars/calendars/ose.py
- pandas_market_calendars/calendars/sifma.py
- pandas_market_calendars/calendars/six.py
- pandas_market_calendars/calendars/sse.py
- pandas_market_calendars/calendars/tase.py
- pandas_market_calendars/calendars/tsx.py
- pandas_market_calendars/market_calendar.py
Added a new property `full_name` to the `MarketCalendar`.
Added the full names for market abbreviations I could find a proper name for.
Fixes #378.
> Add full names for markets

- pandas_market_calendars/calendar_utils.py
- tests/test_utils.py
The existing behavior will inconsistently insert NaT for the open/close time based on the order of the schedules.
> Better merge_schedules outer join handling
