rsheftel/pandas_market_calendars

exchange_calendar_eurex.py

Eurex holidays

---

pandas_market_calendars/calendar_utils.py
pandas_market_calendars/exchange_calendar_eurex.py

Added Eurex holidays

---

pandas_market_calendars/exchange_calendar_eurex.py

was previously using lse defaults and comments

eurex time fixed

---

pandas_market_calendars/exchange_calendar_tsx.py

Took a while to figure out I wasn't crazy and pytz does indeed work correctly

corrected open time and timezone

---

pandas_market_calendars/exchange_calendar_bmf.py
pandas_market_calendars/exchange_calendar_cfe.py
pandas_market_calendars/exchange_calendar_cme.py
pandas_market_calendars/exchange_calendar_eurex.py
pandas_market_calendars/exchange_calendar_ice.py
pandas_market_calendars/exchange_calendar_jpx.py
pandas_market_calendars/exchange_calendar_lse.py
pandas_market_calendars/exchange_calendar_nyse.py
pandas_market_calendars/exchange_calendar_tsx.py
tests/test_cfe_calendar.py
tests/test_nyse_calendar.py

Make default times return TZ aware times

---

docs/calendars.rst
pandas_market_calendars/calendar_utils.py
pandas_market_calendars/exchange_calendar_six.py
tests/test_six_calendar.py

The documentation still needs to be done. And maybe more tests would be useful, which I will probably do soon. However, it would be nice if other developers can already have a look. Thank you.

Six exchange calendar

---

pandas_market_calendars/holidays_jp.py
tests/test_jpx_calendar.py

Slightly better comments and names for JPX calendar; no functional changes.

Fixed test name and comments for JPX calendar

---

pandas_market_calendars/class_registry.py
pandas_market_calendars/market_calendar.py

This should not introduce any functional changes.

Cleanup metaclass code:  less PEP-8 formatting and pylint warnings.

---

pandas_market_calendars/exchange_calendar_asx.py
pandas_market_calendars/holidays_oz.py

Hi rsheftel,
It'd be much appreciated if you could review this pull request on ASX market trading days.
Regards,
pulledlamb

Add ASX market

---

pandas_market_calendars/exchange_calendar_six.py
tests/test_six_calendar.py

Fix for SIX Christmas holidays

---

pandas_market_calendars/market_calendar.py
tests/test_market_calendar.py

Fix bug: `open_at_time` method unable to recognize timezone differences involving date change (details as noted at #112  )

Fix open_at_time #112

---

pandas_market_calendars/exchange_calendar_bse.py

Hi @rsheftel . i have added 2021 holiday cal based on https://www.bseindia.com/static/markets/marketinfo/listholi.aspx
let me know if you need any other details
thanks for the library 👍

Adding 2021 holidays

---

pandas_market_calendars/exchange_calendar_nyse.py
pandas_market_calendars/holidays_nyse.py
tests/test_nyse_calendar.py
tests/test_nyse_calendar_early_years.py

added Juneteenth to the NYSE calendar + some related unit tests

added Juneteenth to NYSE calendar for 2022 onwards

---

pandas_market_calendars/class_registry.py
tests/test_market_calendar.py

In response to #156, I created a simple fix allowing unpickling to work correctly.
All existing tests pass and I added one for pickling with the standard module but I also tested it with jsonpickle, locally.
@rsheftel, and @misantroop, let me know if you think it could be done better or if there are issues I don't realize.
Thanks.

Unpickling #156

---

setup.py

This is the only spot where it would need to change right, @rsheftel?

set pandas>=1.1 in setup.py

---

pandas_market_calendars/exchange_calendar_bse.py

Creating an alias for "NSE - National Stock Exchange - India"

Create an alias for NSE

---

pandas_market_calendars/calendar_registry.py
pandas_market_calendars/exchange_calendar_cme_globex_energy_and_metals.py
pandas_market_calendars/holidays_cme_globex.py
tests/test_exchange_calendar_cme_globex_energy_and_metals.py

CME Globex Energy and Metals Calendar with tests from 2020 through 2022.

CME Globex Energy and Metals tested 2020-2022

---

pandas_market_calendars/exchange_calendar_iex.py

just fixing a small typo in @carterjfulcher's changes and pulling the description from the official website.

Fixes typo, pulls description from IEX website

---

docs/change_log.rst
pandas_market_calendars/exchange_calendar_nyse.py
pandas_market_calendars/market_calendar.py
setup.py
tests/test_market_calendar.py
tests/test_nyse_calendar.py

This PR fixes a couple of things, includng #213. Only minor changes are made so incrementing to 4.0.1 seems most reasonable to me. I also updated change_log.rst and setup.py.

Duplicate fix

---

.github/config_new_release.yml
.github/workflows/check_branch.yml
.github/workflows/releaser.yml
.github/workflows/test_release.yml
.github/workflows/test_runner.yml
docs/conf.py
docs/make_examples.bat
docs/usage.rst
examples/usage.ipynb
pyproject.toml

This PR introduces the new realease management, following the discussion in #208.
This is a draft because I still need to create a CONTRIBUTING.md file and wait for @rsheftel to set the pypi tokens (see 'more detailed description'). After merging this, I will have to finalize the setup with a couple of commits and a few test-PRs.
1. Open PR against the dev branch.
This triggers a workflow that runs tests and checks coverage.
2. Merge PR into dev
This triggeres nothing. It is the opportunity to make adjustments and to merge multiple PRs into dev, to make them a single release.
3. Open PR of dev to main
This triggers a workflow that runs tests, and uploads the package to testpypi, to test the upload and installation of the new version.
4. Merge dev into main
This triggers the final …

Automated Release Management

---

pandas_market_calendars/exchange_calendar_asx.py
pandas_market_calendars/holidays_oz.py
pandas_market_calendars/holidays_uk.py
tests/test_asx_calendar.py
tests/test_lse_calendar.py

add UK and Australia holidays for Queen Elizabeth II's State Funeral

---

docs/change_log.rst
docs/usage.rst
pandas_market_calendars/exchange_calendar_nyse.py
pyproject.toml
setup.py
tests/test_nyse_calendar.py

Valid days fix

---

docs/change_log.rst
docs/usage.rst
pandas_market_calendars/exchange_calendar_bse.py
pyproject.toml
setup.py

Added 2023 BSE holiday calendar

2023 bse holidays

---

pandas_market_calendars/holidays_uk.py
tests/test_lse_calendar.py

add King Charles III's Coronation Day holiday to LSE calendar

---

pyproject.toml

This should fix issue https://github.com/rsheftel/pandas_market_calendars/issues/289 -- just in case it helps having this PR to merge

Add subpackages for inclusion in package build

---

docs/calendars.rst
pandas_market_calendars/calendar_registry.py
pandas_market_calendars/calendars/cme_globex_agriculture.py
pandas_market_calendars/market_calendar.py
tests/test_cme_agriculture_calendar.py
tests/test_exchange_calendar_cme_globex_grains.py

https://www.cmegroup.com/trading/agricultural/grain-and-oilseed.html

Add CME/Globex calendar for grains

---

pandas_market_calendars/calendars/sse.py
pandas_market_calendars/holidays/cn.py

Updated based on latest government announcement: https://www.gov.cn/zhengce/content/202411/content_6986382.htm

China holidays 2025
